[package]
name = "crate2bib-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
crate2bib = { version = "0.1", path = "../crate2bib/"}
tokio = { version = "1.43.0", features = ["macros"] }
