[workspace]
resolver = "2"

members = [
    "crate2bib",
    "crate2bib-app",
    "crate2bib-cli",
    "crate2bib-py"
]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
