[package]
name = "crate2bib"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
crates_io_api = "0.11.0"
semver = "1.0.24"
serde_json = "1.0.135"
serde = { version = "1.0", optional = true }

[features]
default-features = [ "serde"]
serde = [ "dep:serde" ]
