[application]
name = "crate2bib"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "crate2bib"
# base_path = "https://github.com/jonaspleyer/crate2bib/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
